matrix:
  include:
    - language: java
      before_script:
        - cd server
      script:
        - mvn install

    - language: android
      android:
        components:
          #- tools
          - build-tools-28.0.2
          - android-28
          
      before_script:
        - cd FlashMobClient
      script:
        - ./gradlew build 

 

notifications:
  email:
    - andreadv1997@gmail.com
    - lauranardi26@gmail.com
    - mimmo.carapella@gmail.com
  on_success: change
  on_failure: always