language: java
Language: android

env:
- DIR=FlashMobClient
- DIR=server

script:
 - if $DIR==FlashMobClient;
       then cd $DIR && gradle build;
    else cd $DIR && mvn install;
   fi

notifications:
  email:
    - andreadv1997@gmail.com
    - lauranardi26@gmail.com
    - mimmo.carapella@gmail.com
  on_success: change
  on_failure: always