matrix:
  include:
    - language: java
      before_script:
        - cd server
      script:
        - mvn install

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - build-tools-27.0.3
          - android-27
          
      before_script:
        - cd FlashMobClient
      script:
        - ./gradlew build 

 

notifications:
  email:
    - andreadv1997@gmail.com
    - lauranardi26@gmail.com
    - mimmo.carapella@gmail.com
  on_success: change
  on_failure: always