language: java
language: android
sudo: false
install: true

env:
- DIR=FlashMobClient
- DIR=server

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools # needs to be specified even with version below

    # The BuildTools version used by your project
    - build-tools-27.0.1

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-android-support
    - extra-google-google_play_service
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-27
    - sys-img-x86_64-android-27


before_script:
  - apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
  - android list targets
  - echo no | android create avd --force -n test -t android-27 --abi default/x86_64
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
 - if $DIR==FlashMobClient;
       then cd $DIR && gradle build; 
    else cd $DIR %% mvn install;
   fi
 - gradle jacocoTestReport

notifications:
  email:
    - andreadv1997@gmail.com
    - lauranardi26@gmail.com
    - mimmo.carapella@gmail.com
  on_success: never
  on_failure: never
